// A fast, non-browser DOM-shim test: plain `node --test`
// under jsdom, no Playwright/Chromium, driving the real web/tessera-driver.js + web/tessera-html-target.js
// against the same committed, deterministic per-case frame streams tests/web_render.spec.js already
// replays in a real browser (test/web_render_playwright/goldens/<case>-html.frames.jsonl, generated by
// gen_goldens.ml from a native Bridge_runner replay of the committed test/node_pty/traces/<name>.json
// fixtures -- see gen_goldens.ml's own doc comment).
//
// Deliberately reuses the *existing* two oracles web_render.spec.js's browser test already relies on,
// rather than inventing a third: the JSONL golden is the frame stream to ingest, and
// test/web_rendering_traces/goldens/<case>.out's `html:` line is the independent final-DOM-state oracle
// (a full reset built straight from the final terminal snapshot, not derived from the JSONL sequence at
// all). This test asserts the same structural fields that browser test does (columns/row_count/cursor/
// rows/title) via TesseraHtmlTarget's own `probe()`, just under jsdom instead of a real page -- a much
// faster failure signal for a DOM-construction regression (no Chromium, no jsoo/Melange bridge build),
// with the Playwright suite kept as the real-DOM/visual integration layer (screenshots, real fonts/CSS
// layout, and cross-backend (jsoo/Melange) production parity, none of which jsdom can stand in for).

'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { JSDOM } = require('jsdom');

const REPO_ROOT = path.join(__dirname, '..', '..', '..');
const { TesseraDriver } = require(path.join(REPO_ROOT, 'web', 'tessera-driver.js'));
require(path.join(REPO_ROOT, 'web', 'tessera-html-target.js'));
const { TesseraHtmlTarget } = global.Tessera;

const CASES = [
  'dialog-menu-submit',
  'whiptail-menu-cancel',
  'vt-form-edit',
  'vt-scroll-redraw',
  'vt-resize-redraw',
  'vt-shell-session',
];

function readJsonlGolden(caseName) {
  const p = path.join(__dirname, '..', 'goldens', `${caseName}-html.frames.jsonl`);
  return fs
    .readFileSync(p, 'utf8')
    .split('\n')
    .filter((line) => line.length > 0);
}

function readNativeGolden(caseName) {
  const p = path.join(REPO_ROOT, 'test', 'web_rendering_traces', 'goldens', `${caseName}.out`);
  const content = fs.readFileSync(p, 'utf8');
  const htmlLine = content.split('\n').find((line) => line.startsWith('html:'));
  if (!htmlLine) throw new Error(`no html: line in ${p}`);
  return JSON.parse(htmlLine.slice('html:'.length));
}

// TesseraHtmlTarget.mount reads bytes off `host.ownerDocument`, so a jsdom-backed `host` element is
// enough -- no global `document`/`window` needs to exist for the target/driver modules themselves.
function newHost() {
  const dom = new JSDOM('<!doctype html><html><body><div id="host"></div></body></html>');
  return dom.window.document.getElementById('host');
}

for (const caseName of CASES) {
  test(`${caseName}: jsdom-replayed DOM state matches the native replay golden`, () => {
    const host = newHost();
    const target = new TesseraHtmlTarget();
    target.mount(host);
    const errors = [];
    const driver = new TesseraDriver(target, {
      onProtocolError: (reason, details) => errors.push(['protocol', reason, details]),
      onResyncNeeded: (reason, details) => errors.push(['resync', reason, details]),
    });

    for (const line of readJsonlGolden(caseName)) driver.ingest(line);

    assert.deepEqual(errors, []);

    const golden = readNativeGolden(caseName);
    const probe = target.probe();
    assert.equal(probe.columns, golden.frame.columns);
    assert.equal(probe.row_count, golden.frame.row_count);
    assert.deepEqual(probe.cursor, golden.frame.cursor);
    assert.deepEqual(probe.rows, golden.frame.rows);
  });
}
