// The real-terminal trace matrix: for each of
// the six committed test/node_pty/traces/<name>.json cases, on both the jsoo and Melange backends,
// decode the trace (via tessera-trace-decoder.js, loaded in-page), drive create/push/resize/finish
// through a TesseraDriver+TesseraHtmlTarget, and capture every emitted frame JSON string in order.
//
// Two distinct oracles for two distinct properties (fixes round-3 finding #2 -- a JSONL golden's last
// line is finish()'s own delta and cannot be deep-equal to probe()'s full reconstructed DOM):
//  - wire-stream fidelity: the captured ordered frame sequence equals the committed
//    goldens/<case>-html.frames.jsonl golden (generated by test/web_render_playwright/gen_goldens.ml
//    from the same canonical Bridge_runner sequence);
//  - final DOM-state correctness: probe() (the driver's fully-reconstructed live DOM after every
//    frame) deep-equals the *existing* test/web_rendering_traces/goldens/<case>.out file's `html:`
//    line -- an independent full reset built straight from the final terminal snapshot, not derived
//    from the JSONL sequence at all -- including document.title against that same golden's meta.title.
//
// Then a final-state screenshot per case x backend, plus mid-replay checkpoint screenshots for the
// jsoo backend on vt-resize-redraw/vt-scroll-redraw/vt-form-edit.

'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { test, expect } = require('@playwright/test');

const CASES = ['dialog-menu-submit', 'whiptail-menu-cancel', 'vt-form-edit', 'vt-scroll-redraw', 'vt-resize-redraw', 'vt-shell-session'];
const BACKENDS = ['jsoo', 'melange'];
const FIXED_METRICS = { cellWidth: 9, cellHeight: 18, lineHeight: 18, fontFamily: 'Tessera Mono', fontWeight: 400 };
const REPO_ROOT = path.join(__dirname, '..', '..', '..');

function readJsonlGolden(caseName) {
  const p = path.join(__dirname, '..', 'goldens', `${caseName}-html.frames.jsonl`);
  return fs
    .readFileSync(p, 'utf8')
    .split('\n')
    .filter((line) => line.length > 0);
}

function readNativeGolden(caseName) {
  const p = path.join(REPO_ROOT, 'test', 'web_rendering_traces', 'goldens', `${caseName}.out`);
  const content = fs.readFileSync(p, 'utf8');
  const htmlLine = content.split('\n').find((line) => line.startsWith('html:'));
  if (!htmlLine) throw new Error(`no html: line in ${p}`);
  return JSON.parse(htmlLine.slice('html:'.length));
}

async function setUp(page) {
  await page.addInitScript((metrics) => {
    window.__TESSERA_FIXED_METRICS__ = metrics;
  }, FIXED_METRICS);
  await page.goto('/');
  await page.evaluate(async () => {
    await document.fonts.load('400 16px "Tessera Mono"');
    await document.fonts.ready;
  });
}

// Initializes a driver/target/bridge trio for one case+backend and stores it on `window` so a test
// can drive it incrementally across several page.evaluate calls (needed for the checkpoint
// screenshots below).
async function initReplay(page, caseName, backend) {
  return page.evaluate(
    async ({ caseName, backend }) => {
      const traceRes = await fetch('/traces/' + caseName + '.json');
      const trace = await traceRes.json();
      const bridge = await window.TesseraBackends.load(backend);

      const host = document.getElementById('host');
      host.innerHTML = '';
      const target = new window.Tessera.TesseraHtmlTarget();
      target.mount(host);
      target.setMetrics(window.__TESSERA_FIXED_METRICS__);
      const errors = [];
      const driver = new window.Tessera.TesseraDriver(target, {
        onProtocolError: (reason, details) => errors.push(['protocol', reason, details]),
        onResyncNeeded: (reason, details) => errors.push(['resync', reason, details]),
      });

      window.__replay = { trace, bridge, driver, target, errors, frames: [], eventIndex: 0, started: false };
    },
    { caseName, backend }
  );
}

// Advances the stored replay by exactly one step (the initial create() call, then one event per
// call), ingesting the resulting frame through the driver, until `untilEventIndex` (exclusive) events
// have been consumed, or to completion (including the trailing finish()) when `untilEventIndex` is
// null.
async function advanceReplay(page, untilEventIndex) {
  return page.evaluate(async (untilEventIndex) => {
    const state = window.__replay;
    if (!state.started) {
      const frame = state.bridge.create('html', 1, state.trace.columns, state.trace.rows);
      state.frames.push(frame);
      state.driver.ingest(frame);
      state.started = true;
    }
    const stop = untilEventIndex === null ? state.trace.events.length : untilEventIndex;
    while (state.eventIndex < stop) {
      const event = state.trace.events[state.eventIndex];
      let frame;
      if (event.kind === 'data') {
        const text = window.Tessera.decodeTraceBytes(event.bytes_base64);
        frame = state.bridge.push(text);
      } else {
        frame = state.bridge.resize(event.columns, event.rows);
      }
      state.frames.push(frame);
      state.driver.ingest(frame);
      state.eventIndex += 1;
    }
    if (untilEventIndex === null) {
      const frame = state.bridge.finish();
      state.frames.push(frame);
      state.driver.ingest(frame);
    }
    return {
      frames: state.frames.slice(),
      errors: state.errors.slice(),
      probe: state.target.probe(),
      title: document.title,
      done: untilEventIndex === null,
    };
  }, untilEventIndex);
}

for (const caseName of CASES) {
  for (const backend of BACKENDS) {
    test(`${caseName} [${backend}]: wire-stream matches the JSONL golden`, async ({ page }) => {
      await setUp(page);
      await initReplay(page, caseName, backend);
      const result = await advanceReplay(page, null);
      expect(result.errors).toEqual([]);
      const golden = readJsonlGolden(caseName);
      expect(result.frames).toEqual(golden);
      const finalMeta = JSON.parse(result.frames[result.frames.length - 1]).meta;
      const goldenFinalGeneration = JSON.parse(golden[golden.length - 1]).meta.generation;
      expect(finalMeta.generation).toBe(goldenFinalGeneration);
    });

    test(`${caseName} [${backend}]: final DOM state matches the native replay golden`, async ({ page }) => {
      await setUp(page);
      await initReplay(page, caseName, backend);
      const result = await advanceReplay(page, null);
      expect(result.errors).toEqual([]);
      const golden = readNativeGolden(caseName);
      expect(result.probe.columns).toBe(golden.frame.columns);
      expect(result.probe.row_count).toBe(golden.frame.row_count);
      expect(result.probe.cursor).toEqual(golden.frame.cursor);
      expect(result.probe.rows).toEqual(golden.frame.rows);
      const rowTexts = result.probe.rows.map((r) => r.text);
      const goldenTexts = golden.frame.rows.map((r) => r.text);
      expect(rowTexts).toEqual(goldenTexts);
      if (golden.meta.title !== undefined && golden.meta.title !== null) {
        expect(result.title).toBe(golden.meta.title);
      }
    });

    test(`${caseName} [${backend}]: final screenshot`, async ({ page }) => {
      await setUp(page);
      await initReplay(page, caseName, backend);
      await advanceReplay(page, null);
      await expect(page.locator('#host')).toHaveScreenshot(`${caseName}-${backend}-final.png`);
    });
  }
}

// Mid-replay checkpoint screenshots (jsoo only -- cross-backend equivalence for these intermediate
// frames is already proven structurally by test/web_bridge_equivalence's every-frame assertion, so
// this is not duplicated per backend).
const CHECKPOINTS = {
  'vt-resize-redraw': (trace) => trace.events.findIndex((e) => e.kind === 'resize') + 1,
  'vt-scroll-redraw': (trace) => Math.floor(trace.events.length / 2),
  'vt-form-edit': (trace) => Math.floor(trace.events.length / 2),
};

for (const caseName of Object.keys(CHECKPOINTS)) {
  test(`${caseName} [jsoo]: checkpoint screenshot mid-replay, then final`, async ({ page }) => {
    await setUp(page);
    await initReplay(page, caseName, 'jsoo');
    const trace = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, 'test', 'node_pty', 'traces', `${caseName}.json`), 'utf8'));
    const stopAt = CHECKPOINTS[caseName](trace);
    const checkpointResult = await advanceReplay(page, stopAt);
    expect(checkpointResult.errors).toEqual([]);
    await expect(page.locator('#host')).toHaveScreenshot(`${caseName}-jsoo-checkpoint.png`);
    const finalResult = await advanceReplay(page, null);
    expect(finalResult.errors).toEqual([]);
    await expect(page.locator('#host')).toHaveScreenshot(`${caseName}-jsoo-final-after-checkpoint.png`);
  });
}
