(executable
 (name winsize_probe)
 (modules winsize_probe)
 (libraries tessera_proxy_platform_linux tessera_proxy_platform unix)
 (enabled_if
  (= %{system} linux)))

(test
 (name platform_linux_test)
 (modules platform_linux_test)
 (libraries
  fmt
  tessera_test_support
  tessera_foundation
  tessera
  tessera_lwt
  tessera_proxy_platform
  tessera_proxy_platform_linux
  tessera_proxy_linux
  lwt
  lwt.unix
  unix)
 (action
  (run %{test} %{exe:winsize_probe.exe}))
 (enabled_if
  (= %{system} linux)))

(library
 (name tessera_test_terminfo_resource)
 (modules terminfo_resource_test)
 (inline_tests
  (modes byte native))
 (libraries tessera_proxy_platform unix)
 (preprocess
  (pps ppx_expect)))

(alias
 (name test-proxy-platform-linux)
 (deps
  (alias runtest)))
