(library
 (name tessera_test_renderer)
 (modules cursor editing scrolling screens invariants allocation)
 (inline_tests
  (modes byte native))
 (libraries
  fmt
  tessera_test_support
  tessera_foundation
  tessera_model
  tessera_renderer)
 (preprocess
  (pps ppx_expect)))

(alias
 (name test-renderer)
 (deps
  (alias runtest)))
