(library
 (name tessera_test_proxy_linux_fake_platform)
 (modules fake_platform)
 (libraries tessera_proxy_platform unix))

(library
 (name tessera_test_proxy_linux)
 (modules
  resize_loop_test
  session_test
  contract_test
  observer_server_test
  checkpoint_test
  terminal_selection_test
  web_server_test)
 (inline_tests
  (modes byte native))
 (libraries
  fmt
  tessera_test_support
  tessera_foundation
  tessera_model
  tessera
  tessera_lwt
  tessera_proxy_platform
  tessera_proxy_observer
  tessera_proxy_protocol
  tessera_proxy_web_protocol
  tessera_web_rendering
  tessera_proxy_linux
  tessera_test_proxy_linux_fake_platform
  lwt
  lwt.unix
  unix
  bigstringaf
  httpun
  httpun-ws
  httpun-ws-lwt-unix)
 (preprocess
  (pps ppx_expect)))

(alias
 (name test-proxy-linux)
 (deps
  (alias runtest)))
