(* Generates web_assets.ml: the fixed, compiled-in route table {!Web_server} serves, from the checked-in web/
   directory -- because tessera-proxy is an installed executable (public_name tessera-proxy) that cannot assume a
   source checkout is nearby at runtime. Run by a dune (rule ...) at build time (see dune), not a manual developer
   command like gen_goldens.ml: the emitted module must always be in sync with web/, and there is nothing here for a
   developer to review before committing (there is no output committed to the tree at all). *)

let read_file path =
  let ic = open_in_bin path in
  Fun.protect ~finally:(fun () -> close_in ic) (fun () -> really_input_string ic (in_channel_length ic))

let routes web_dir =
  let asset name = Filename.concat web_dir name in
  [
    ("/", "text/html; charset=utf-8", asset "index.html");
    ("/tessera-decode.js", "text/javascript; charset=utf-8", asset "tessera-decode.js");
    ("/tessera-driver.js", "text/javascript; charset=utf-8", asset "tessera-driver.js");
    ("/tessera-html-target.js", "text/javascript; charset=utf-8", asset "tessera-html-target.js");
    ("/proxy-input.js", "text/javascript; charset=utf-8", asset "proxy-input.js");
    ("/tessera.css", "text/css; charset=utf-8", asset "tessera.css");
    ("/proxy-web.js", "text/javascript; charset=utf-8", asset "proxy-web.js");
    ( "/fonts/jetbrains-mono-latin-400-normal.woff2",
      "font/woff2",
      Filename.concat (asset "fonts") "jetbrains-mono-latin-400-normal.woff2" );
  ]

let () =
  let web_dir = if Array.length Sys.argv > 1 then Sys.argv.(1) else "web" in
  print_string
    "(* Generated by lib/proxy_linux/gen_web_assets.ml from the web/ directory at build time -- do not edit by hand. \
     *)\n\n";
  print_string "let routes : (string * string * string) list =\n  [\n";
  List.iter
    (fun (route, content_type, path) ->
      let content = read_file path in
      Printf.printf "    (%S, %S, %S);\n" route content_type content)
    (routes web_dir);
  print_string "  ]\n"
