name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  versions:
    uses: ./.github/workflows/ocaml-versions.yml
  build:
    needs: versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.versions.outputs.images_matrix) }}
    steps:
    - name: checkout
      uses: actions/checkout@v7
      with:
        submodules: true
    - name: devcontainer
      uses: ./.github/workflows/actions/devcontainer
      id: devcontainer
      env:
        OCAML_VERSION: ${{ matrix.ocaml_version }}
      with:
        variant: ${{ matrix.ocaml_version }}
        platform: ${{ matrix.platform }}
    - name: setup
      run: |
        echo 'EXEC=${{ steps.devcontainer.outputs.exec }}' >> $GITHUB_ENV
    - name: info
      run: |
        ${{ env.EXEC }} sh -c '
          uname -m
          dpkg --print-architecture
          getconf LONG_BIT
          opam exec -- ocamlc -config | grep "^architecture:"
          opam exec -- ocaml --version
        '
    - name: build
      run: |
        ${{ env.EXEC }} make build
    - name: test
      run: |
        ${{ env.EXEC }} make test
    - name: jsoo
      run: |
        ${{ env.EXEC }} make jsoo
    - name: melange
      run: |
        ${{ env.EXEC }} make melange
    - name: format-check
      run: |
        ${{ env.EXEC }} make format-check
    - name: verify repository is unchanged
      run: |
        make pristine
