name: images

on:
  push:
    branches:
      - '**'

jobs:
  versions:
    uses: ./.github/workflows/ocaml-versions.yml
  devcontainer:
    needs: versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.versions.outputs.images_matrix) }}
    permissions:
      packages: write
    steps:
    - name: checkout
      uses: actions/checkout@v7
      with:
        submodules: true
    - name: image
      id: devcontainer
      uses: ./.github/workflows/actions/devcontainer
      env:
        OCAML_VERSION: ${{ matrix.ocaml_version }}
      with:
        variant: ${{ matrix.ocaml_version }}
        platform: ${{ matrix.platform }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: smoke test (devcontainer)
      run: |
        ${{ steps.devcontainer.outputs.exec }} sh -ceu '
          echo "hello world"
        '
  devcontainers-cli:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            platform: linux/amd64
    permissions:
      packages: write
    steps:
    - name: checkout
      uses: actions/checkout@v7
    - name: image
      id: devcontainer-cli
      uses: ./.github/workflows/actions/devcontainer
      with:
        name: devcontainers-cli
        config: .devcontainer/devcontainers.cli/devcontainer.json
        platform: ${{ matrix.platform }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: smoke test
      run: ${{ steps.devcontainer-cli.outputs.exec }} echo "hello world"
